// Trinity Music Theory Quiz Questions by Level

export type MusicTheoryLevel = "Level 1" | "Level 2" | "Grade 1" | "Grade 2" | "Grade 3" | "Grade 4";

export interface QuizQuestion {
  id: string;
  level: MusicTheoryLevel;
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  category: string; // "notes", "time-signatures", "rhythm", "scales", "intervals", "chords", "keys"
}

export const musicTheoryQuestions: QuizQuestion[] = [
  // ═════ LEVEL 1 ═════
  {
    id: "l1-1",
    level: "Level 1",
    category: "notes",
    question: "Which note is shown on the treble clef?",
    options: ["C", "D", "E", "F"],
    correctAnswer: "E",
    explanation: "This is the note E on the treble clef, located on the second line from the top.",
  },
  {
    id: "l1-2",
    level: "Level 1",
    category: "notes",
    question: "How many lines are on the musical staff?",
    options: ["3", "4", "5", "6"],
    correctAnswer: "5",
    explanation: "The musical staff has 5 lines and 4 spaces between them.",
  },
  {
    id: "l1-3",
    level: "Level 1",
    category: "rhythm",
    question: "How many beats does a whole note get in 4/4 time?",
    options: ["1", "2", "4", "8"],
    correctAnswer: "4",
    explanation: "A whole note gets 4 beats in common time (4/4).",
  },
  {
    id: "l1-4",
    level: "Level 1",
    category: "time-signatures",
    question: "What does 4/4 time mean?",
    options: ["4 notes per bar", "4 beats per bar", "4 quarter notes", "4 measures"],
    correctAnswer: "4 beats per bar",
    explanation: "4/4 time means there are 4 beats in each measure, with the quarter note getting one beat.",
  },
  {
    id: "l1-5",
    level: "Level 1",
    category: "notes",
    question: "Which of these is NOT a natural note?",
    options: ["C", "F#", "G", "A"],
    correctAnswer: "F#",
    explanation: "F# is a sharp note (raised by a semitone). The natural notes are C, D, E, F, G, A, B.",
  },
  {
    id: "l1-6",
    level: "Level 1",
    category: "rhythm",
    question: "How many beats does a half note get in 4/4 time?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
    explanation: "A half note gets 2 beats in 4/4 time.",
  },
  {
    id: "l1-7",
    level: "Level 1",
    category: "notes",
    question: "What is the order of the white keys on a piano starting from C?",
    options: ["C D E F G A B", "A B C D E F G", "C D F G A B E", "D E F G A B C"],
    correctAnswer: "C D E F G A B",
    explanation: "The pattern of white keys repeats: C, D, E, F, G, A, B, then back to C.",
  },

  // ═════ LEVEL 2 ═════
  {
    id: "l2-1",
    level: "Level 2",
    category: "notes",
    question: "What is a sharp symbol (#)?",
    options: ["Lowers a note by a semitone", "Raises a note by a semitone", "Doubles the note length", "Means to play loudly"],
    correctAnswer: "Raises a note by a semitone",
    explanation: "A sharp (#) raises a note by one semitone (one half step).",
  },
  {
    id: "l2-2",
    level: "Level 2",
    category: "notes",
    question: "What is a flat symbol (♭)?",
    options: ["Raises a note by a semitone", "Lowers a note by a semitone", "Cancels an accidental", "Means to play softly"],
    correctAnswer: "Lowers a note by a semitone",
    explanation: "A flat (♭) lowers a note by one semitone (one half step).",
  },
  {
    id: "l2-3",
    level: "Level 2",
    category: "scales",
    question: "How many semitones are in a whole step?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
    explanation: "A whole step (or whole tone) consists of 2 semitones.",
  },
  {
    id: "l2-4",
    level: "Level 2",
    category: "time-signatures",
    question: "In 3/4 time, how many beats are in each bar?",
    options: ["2", "3", "4", "6"],
    correctAnswer: "3",
    explanation: "3/4 time (also called waltz time) has 3 beats per measure.",
  },
  {
    id: "l2-5",
    level: "Level 2",
    category: "notes",
    question: "What is a natural symbol (♮)?",
    options: ["Raises a note", "Lowers a note", "Cancels a sharp or flat", "Doubles the note"],
    correctAnswer: "Cancels a sharp or flat",
    explanation: "A natural (♮) cancels any previous sharp or flat on that note.",
  },
  {
    id: "l2-6",
    level: "Level 2",
    category: "rhythm",
    question: "What is a dotted note?",
    options: ["A note that's half as long", "A note that's 1.5 times as long", "A note that's twice as long", "A silent note"],
    correctAnswer: "A note that's 1.5 times as long",
    explanation: "A dot after a note increases its duration by half its original value.",
  },
  {
    id: "l2-7",
    level: "Level 2",
    category: "intervals",
    question: "What interval is from C to E?",
    options: ["Major second", "Major third", "Perfect fourth", "Perfect fifth"],
    correctAnswer: "Major third",
    explanation: "From C to E is 4 semitones, which is a major third.",
  },

  // ═════ GRADE 1 ═════
  {
    id: "g1-1",
    level: "Grade 1",
    category: "scales",
    question: "What is the pattern of a major scale?",
    options: ["W-H-W-W-H-W-W", "W-W-H-W-W-W-H", "H-W-W-W-H-W-W", "W-H-W-W-W-H-W"],
    correctAnswer: "W-H-W-W-H-W-W",
    explanation: "Major scale pattern: Whole-Half-Whole-Whole-Half-Whole-Whole step intervals.",
  },
  {
    id: "g1-2",
    level: "Grade 1",
    category: "keys",
    question: "How many sharps are in the key of G major?",
    options: ["0", "1", "2", "3"],
    correctAnswer: "1",
    explanation: "G major has 1 sharp (F#). Use the Circle of Fifths to identify keys.",
  },
  {
    id: "g1-3",
    level: "Grade 1",
    category: "keys",
    question: "How many flats are in the key of F major?",
    options: ["0", "1", "2", "3"],
    correctAnswer: "1",
    explanation: "F major has 1 flat (B♭).",
  },
  {
    id: "g1-4",
    level: "Grade 1",
    category: "intervals",
    question: "What interval is from C to G?",
    options: ["Perfect fourth", "Perfect fifth", "Major sixth", "Perfect octave"],
    correctAnswer: "Perfect fifth",
    explanation: "From C to G is 7 semitones, which is a perfect fifth.",
  },
  {
    id: "g1-5",
    level: "Grade 1",
    category: "chords",
    question: "What notes make up a C major triad?",
    options: ["C-D-E", "C-E-G", "C-E♭-G", "C-F-G"],
    correctAnswer: "C-E-G",
    explanation: "A C major triad is built on the 1st, 3rd, and 5th degrees of the C scale: C-E-G.",
  },
  {
    id: "g1-6",
    level: "Grade 1",
    category: "time-signatures",
    question: "In 2/4 time, the quarter note gets how many beats?",
    options: ["1", "2", "4", "8"],
    correctAnswer: "1",
    explanation: "In 2/4 time, the quarter note (4) gets 1 beat, and there are 2 beats per bar.",
  },
  {
    id: "g1-7",
    level: "Grade 1",
    category: "scales",
    question: "What is the relative minor of C major?",
    options: ["A minor", "D minor", "E minor", "G minor"],
    correctAnswer: "A minor",
    explanation: "The relative minor is 3 semitones (a minor third) below the major key. C - 3 semitones = A.",
  },

  // ═════ GRADE 2 ═════
  {
    id: "g2-1",
    level: "Grade 2",
    category: "keys",
    question: "How many sharps are in D major?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
    explanation: "D major has 2 sharps (F# and C#).",
  },
  {
    id: "g2-2",
    level: "Grade 2",
    category: "keys",
    question: "How many flats are in B♭ major?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
    explanation: "B♭ major has 2 flats (B♭ and E♭).",
  },
  {
    id: "g2-3",
    level: "Grade 2",
    category: "scales",
    question: "What type of scale has the pattern: H-W-H-W-H-W-W?",
    options: ["Major scale", "Natural minor scale", "Harmonic minor scale", "Melodic minor scale"],
    correctAnswer: "Natural minor scale",
    explanation: "The natural minor scale has the pattern: Half-Whole-Half-Whole-Half-Whole-Whole.",
  },
  {
    id: "g2-4",
    level: "Grade 2",
    category: "chords",
    question: "What notes make up an A minor triad?",
    options: ["A-C-E", "A-C#-E", "A-C-E♭", "A-D-E"],
    correctAnswer: "A-C-E",
    explanation: "An A minor triad is: A (root), C (minor third), E (perfect fifth).",
  },
  {
    id: "g2-5",
    level: "Grade 2",
    category: "intervals",
    question: "How many semitones are in a major third?",
    options: ["3", "4", "5", "6"],
    correctAnswer: "4",
    explanation: "A major third spans 4 semitones (e.g., C to E).",
  },
  {
    id: "g2-6",
    level: "Grade 2",
    category: "time-signatures",
    question: "What is compound time?",
    options: ["Time with irregular beats", "Time where the beat divides into 3", "Time where the beat divides into 2", "Time with more than 4 beats"],
    correctAnswer: "Time where the beat divides into 3",
    explanation: "Compound time has a dotted note as the beat, dividing into 3 parts (e.g., 6/8, 9/8, 12/8).",
  },
  {
    id: "g2-7",
    level: "Grade 2",
    category: "scales",
    question: "What is the relative major of E minor?",
    options: ["E major", "G major", "D major", "A major"],
    correctAnswer: "G major",
    explanation: "The relative major is 3 semitones above the minor key. E + 3 semitones = G.",
  },

  // ═════ GRADE 3 ═════
  {
    id: "g3-1",
    level: "Grade 3",
    category: "keys",
    question: "How many sharps are in A major?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "3",
    explanation: "A major has 3 sharps (F#, C#, and G#).",
  },
  {
    id: "g3-2",
    level: "Grade 3",
    category: "keys",
    question: "How many flats are in E♭ major?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "3",
    explanation: "E♭ major has 3 flats (B♭, E♭, and A♭).",
  },
  {
    id: "g3-3",
    level: "Grade 3",
    category: "scales",
    question: "What makes the harmonic minor scale different from natural minor?",
    options: ["Raised 6th degree", "Raised 7th degree", "Lowered 2nd degree", "Raised 3rd degree"],
    correctAnswer: "Raised 7th degree",
    explanation: "The harmonic minor scale raises the 7th degree by a semitone to create a stronger leading tone.",
  },
  {
    id: "g3-4",
    level: "Grade 3",
    category: "chords",
    question: "What notes make up a G dominant 7th chord?",
    options: ["G-B-D-F", "G-B-D-F#", "G-B♭-D-F", "G-B-D-E"],
    correctAnswer: "G-B-D-F",
    explanation: "A dominant 7th chord is a major triad plus a minor 7th above the root.",
  },
  {
    id: "g3-5",
    level: "Grade 3",
    category: "intervals",
    question: "How many semitones are in a tritone?",
    options: ["5", "6", "7", "8"],
    correctAnswer: "6",
    explanation: "A tritone (augmented 4th or diminished 5th) spans 6 semitones.",
  },
  {
    id: "g3-6",
    level: "Grade 3",
    category: "time-signatures",
    question: "In 6/8 time, what note gets the beat?",
    options: ["Quarter note", "Half note", "Dotted quarter note", "Eighth note"],
    correctAnswer: "Dotted quarter note",
    explanation: "In 6/8 time, the dotted quarter note gets the beat (compound duple time).",
  },
  {
    id: "g3-7",
    level: "Grade 3",
    category: "scales",
    question: "What is the melodic minor scale?",
    options: [
      "Natural minor with raised 6th and 7th ascending",
      "Natural minor with lowered 6th and 7th",
      "Major scale with lowered 3rd",
      "Major scale with raised 7th",
    ],
    correctAnswer: "Natural minor with raised 6th and 7th ascending",
    explanation: "The melodic minor raises the 6th and 7th degrees when ascending, but returns to natural minor descending.",
  },

  // ═════ GRADE 4 ═════
  {
    id: "g4-1",
    level: "Grade 4",
    category: "keys",
    question: "How many sharps are in E major?",
    options: ["3", "4", "5", "6"],
    correctAnswer: "4",
    explanation: "E major has 4 sharps (F#, C#, G#, and D#).",
  },
  {
    id: "g4-2",
    level: "Grade 4",
    category: "keys",
    question: "How many flats are in A♭ major?",
    options: ["2", "3", "4", "5"],
    correctAnswer: "4",
    explanation: "A♭ major has 4 flats (B♭, E♭, A♭, and D♭).",
  },
  {
    id: "g4-3",
    level: "Grade 4",
    category: "chords",
    question: "What notes make up an F major 7th chord?",
    options: ["F-A-C-E♭", "F-A-C-E", "F-A♭-C-E", "F-A-C-D"],
    correctAnswer: "F-A-C-E♭",
    explanation: "A major 7th chord is a major triad plus a major 7th above the root.",
  },
  {
    id: "g4-4",
    level: "Grade 4",
    category: "scales",
    question: "What is the enharmonic equivalent of C#?",
    options: ["D♭", "B#", "D", "C♭"],
    correctAnswer: "D♭",
    explanation: "Enharmonic equivalents are notes that sound the same but are written differently. C# = D♭.",
  },
  {
    id: "g4-5",
    level: "Grade 4",
    category: "intervals",
    question: "What is an augmented interval?",
    options: ["An interval that's one semitone wider than major", "An interval that's one semitone narrower", "An interval with doubled notes", "An interval that spans an octave"],
    correctAnswer: "An interval that's one semitone wider than major",
    explanation: "An augmented interval is one semitone wider than a perfect or major interval.",
  },
  {
    id: "g4-6",
    level: "Grade 4",
    category: "time-signatures",
    question: "In 9/8 time, how many beats per measure?",
    options: ["6", "8", "9", "3"],
    correctAnswer: "3",
    explanation: "9/8 time is compound triple (3 dotted quarter note beats per measure).",
  },
  {
    id: "g4-7",
    level: "Grade 4",
    category: "chords",
    question: "What is a diminished triad?",
    options: [
      "Root, minor 3rd, perfect 5th",
      "Root, major 3rd, flat 5th",
      "Root, minor 3rd, flat 5th",
      "Root, major 3rd, perfect 5th",
    ],
    correctAnswer: "Root, minor 3rd, flat 5th",
    explanation: "A diminished triad has a root, minor third, and diminished (flat) fifth.",
  },
];

export function getQuestionsByLevel(level: MusicTheoryLevel): QuizQuestion[] {
  return musicTheoryQuestions.filter((q) => q.level === level);
}

export function getRandomQuestions(level: MusicTheoryLevel, count: number = 5): QuizQuestion[] {
  const levelQuestions = getQuestionsByLevel(level);
  const shuffled = [...levelQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, levelQuestions.length));
}
