// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read raw env values (Vite may include quotes if .env contains them).
const rawUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Sanitize by trimming and stripping surrounding quotes if present.
const stripQuotes = (s?: string) => s?.trim().replace(/^['"]|['"]$/g, "") || "";
const SUPABASE_URL = stripQuotes(rawUrl);
const SUPABASE_PUBLISHABLE_KEY = stripQuotes(rawKey);

// Remove stale auth tokens from any previous Supabase project — prevents users needing to clear cache.
try {
  const currentRef = "tychkyunjfbkksyxknhn";
  const stale: string[] = [];
  for (let i = 0; i < localStorage.length; i++) {
    const k = localStorage.key(i);
    if (k && k.startsWith("sb-") && !k.includes(currentRef)) stale.push(k);
  }
  stale.forEach(k => localStorage.removeItem(k));
} catch (_) {}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use Web Locks API when available so Supabase never hits the 5000ms
// fallback-lock timeout warning. Falls back to immediate execution when
// Web Locks isn't supported (rare, non-Chromium mobile browsers).
const authLock = (
  name: string,
  _acquireTimeout: number,
  fn: () => Promise<unknown>,
): Promise<unknown> => {
  if (typeof navigator !== "undefined" && navigator.locks) {
    return navigator.locks.request(name, fn as () => Promise<void>);
  }
  return fn();
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: authLock,
  }
});

// Helpful dev-time diagnostics: warn if envs look missing or malformed.
if (import.meta.env.DEV) {
  try {
    const missing = [];
    if (!SUPABASE_URL) missing.push("VITE_SUPABASE_URL");
    if (!SUPABASE_PUBLISHABLE_KEY) missing.push("VITE_SUPABASE_PUBLISHABLE_KEY");

    if (missing.length) {
      // eslint-disable-next-line no-console
      console.warn(`[supabase] Missing env vars: ${missing.join(", ")}. Check your .env and restart dev server.`);
    } else {
      // eslint-disable-next-line no-console
      console.debug(`[supabase] initialized with URL: ${SUPABASE_URL} (key present: ${Boolean(SUPABASE_PUBLISHABLE_KEY)})`);
    }
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn("[supabase] Error during env diagnostics:", err);
  }
}